import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google"
import { ThemeProvider } from "@/components/provider/theme.provider";
import QueryProvider from "@/components/provider/query.provider";
import { Toaster } from "@/components/ui/sonner";
import SessionProvider from "@/components/provider/session.provider";
import "./global.css";

const spaceGrotesk = Space_Grotesk({
  weight: ["500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-spaceGrotesk"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <SessionProvider>
      <QueryProvider>
        <html lang="en" suppressHydrationWarning>
          <body
          >
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <main>{children}</main>
              <Toaster richColors position="top-center" />
            </ThemeProvider>
          </body>
        </html>
      </QueryProvider >
    </SessionProvider>
  );
}
